"""
Property-based tests for infrastructure check.

# Feature: deploy-readiness-audit, Property 14: No latest image tags in docker-compose
# Feature: deploy-readiness-audit, Property 13: All required env vars documented in .env.example

Validates: Requirements 8.4, 8.6
"""
from __future__ import annotations

import tempfile
from pathlib import Path

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from scripts.checks.infrastructure import (
    REQUIRED_ENV_VARS,
    _is_latest_tag,
    check_env_example_completeness,
    check_no_latest_image_tags,
)

# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------

# Valid version tag strings (not "latest", not empty, not all-digits)
_tag_chars = st.characters(
    whitelist_categories=("Lu", "Ll", "Nd"),
    whitelist_characters=".-_",
)

pinned_tag_strategy = st.builds(
    lambda prefix, rest: prefix + rest,
    prefix=st.text(
        alphabet="abcdefghijklmnopqrstuvwxyz0123456789",
        min_size=1,
        max_size=5,
    ),
    rest=st.text(
        alphabet="abcdefghijklmnopqrstuvwxyz0123456789.-_",
        min_size=0,
        max_size=15,
    ),
).filter(lambda t: t != "latest" and not t.isdigit() and t.strip())

# Image name without tag (simple alphanumeric)
image_name_strategy = st.text(
    alphabet="abcdefghijklmnopqrstuvwxyz0123456789-_/",
    min_size=1,
    max_size=30,
).filter(lambda s: s.strip() and not s.startswith("/") and not s.endswith("/"))

# A pinned image reference: name:tag
pinned_image_strategy = st.builds(
    lambda name, tag: f"{name}:{tag}",
    name=image_name_strategy,
    tag=pinned_tag_strategy,
)

# A "latest" image reference (explicit or implicit)
latest_image_strategy = st.one_of(
    # Explicit :latest
    st.builds(lambda name: f"{name}:latest", name=image_name_strategy),
    # Implicit (no tag)
    image_name_strategy,
)

# Service name strategy — must start with a letter so YAML doesn't parse it as a number
service_name_strategy = st.builds(
    lambda prefix, rest: prefix + rest,
    prefix=st.text(alphabet="abcdefghijklmnopqrstuvwxyz", min_size=1, max_size=1),
    rest=st.text(alphabet="abcdefghijklmnopqrstuvwxyz0123456789-", min_size=0, max_size=19),
).filter(str.strip)

# Subset of REQUIRED_ENV_VARS (at least one missing)
missing_vars_strategy = st.lists(
    st.sampled_from(REQUIRED_ENV_VARS),
    min_size=1,
    max_size=len(REQUIRED_ENV_VARS),
    unique=True,
)

# Safe value strings for env var values
safe_value_strategy = st.text(
    alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_./:",
    min_size=0,
    max_size=50,
)


# ---------------------------------------------------------------------------
# Property 14: No latest image tags in docker-compose
# ---------------------------------------------------------------------------

@given(
    service_name=service_name_strategy,
    image=pinned_image_strategy,
)
@settings(max_examples=100)
def test_pinned_image_tag_never_flagged(service_name: str, image: str):
    """
    # Feature: deploy-readiness-audit, Property 14: No latest image tags in docker-compose

    For any custom service image declaration with a pinned (non-latest) version tag,
    the checker SHALL NOT produce a failure — pinned tags are always acceptable.

    Validates: Requirements 8.6
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)
        compose = tmp_path / "docker-compose.full.yml"
        compose.write_text(f"""
services:
  {service_name}:
    image: {image}
""")
        details, failures = check_no_latest_image_tags(compose, {service_name})
        assert failures == [], (
            f"Expected no failures for pinned image {image!r} on service "
            f"{service_name!r}, but got: {failures}"
        )


@given(
    service_name=service_name_strategy,
    image=latest_image_strategy,
)
@settings(max_examples=100)
def test_latest_image_tag_always_flagged(service_name: str, image: str):
    """
    # Feature: deploy-readiness-audit, Property 14: No latest image tags in docker-compose

    For any custom service image declaration that uses the `latest` tag (explicitly
    or implicitly), the checker SHALL produce at least one failure.

    Validates: Requirements 8.6
    """
    # Skip images that happen to look pinned (e.g. "a:v1" generated by image_name_strategy)
    # We only want truly latest images
    if ":" in image and not image.endswith(":latest"):
        # This image has a non-latest tag — skip
        return

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)
        compose = tmp_path / "docker-compose.full.yml"
        compose.write_text(f"""
services:
  {service_name}:
    image: {image}
""")
        details, failures = check_no_latest_image_tags(compose, {service_name})
        assert len(failures) >= 1, (
            f"Expected at least one failure for latest image {image!r} on service "
            f"{service_name!r}, but got no failures"
        )


@given(
    service_name=service_name_strategy,
)
@settings(max_examples=100)
def test_build_only_service_never_flagged(service_name: str):
    """
    # Feature: deploy-readiness-audit, Property 14: No latest image tags in docker-compose

    For any service that uses only a `build:` stanza with no `image:` key,
    the checker SHALL NOT produce a failure — build-only services are not
    pulled from a registry and cannot have a `latest` registry tag.

    Validates: Requirements 8.6
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)
        compose = tmp_path / "docker-compose.full.yml"
        compose.write_text(f"""
services:
  {service_name}:
    build:
      context: ../some/path
      dockerfile: Dockerfile
""")
        details, failures = check_no_latest_image_tags(compose, {service_name})
        assert failures == [], (
            f"Expected no failures for build-only service {service_name!r}, "
            f"but got: {failures}"
        )


@given(
    pinned_tag=pinned_tag_strategy,
)
@settings(max_examples=100)
def test_is_latest_tag_rejects_pinned_tags(pinned_tag: str):
    """
    # Feature: deploy-readiness-audit, Property 14: No latest image tags in docker-compose

    For any non-latest, non-empty tag string, _is_latest_tag SHALL return False.

    Validates: Requirements 8.6
    """
    image = f"myimage:{pinned_tag}"
    result = _is_latest_tag(image)
    assert result is False, (
        f"Expected _is_latest_tag({image!r}) to be False for pinned tag "
        f"{pinned_tag!r}, but got True"
    )


@given(
    image_name=image_name_strategy,
)
@settings(max_examples=100)
def test_is_latest_tag_accepts_implicit_latest(image_name: str):
    """
    # Feature: deploy-readiness-audit, Property 14: No latest image tags in docker-compose

    For any image name without an explicit tag, _is_latest_tag SHALL return True
    (implicit latest).

    Validates: Requirements 8.6
    """
    # Only test names without colons (no tag)
    if ":" in image_name:
        return
    result = _is_latest_tag(image_name)
    assert result is True, (
        f"Expected _is_latest_tag({image_name!r}) to be True for image "
        f"with no tag (implicit latest), but got False"
    )


# ---------------------------------------------------------------------------
# Property 13: All required env vars documented in .env.example
# ---------------------------------------------------------------------------

@given(
    missing_vars=missing_vars_strategy,
    present_values=st.lists(safe_value_strategy, min_size=0, max_size=10),
)
@settings(max_examples=100)
def test_missing_required_vars_always_produce_failures(
    missing_vars: list[str],
    present_values: list[str],
):
    """
    # Feature: deploy-readiness-audit, Property 13: All required env vars documented in .env.example

    For any subset of required environment variables that are absent from
    infra/.env.example, the checker SHALL produce exactly one failure per
    missing variable.

    Validates: Requirements 8.4
    """
    present_vars = [v for v in REQUIRED_ENV_VARS if v not in missing_vars]

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)
        env_example = tmp_path / ".env.example"

        lines = [f"{var}=somevalue\n" for var in present_vars]
        env_example.write_text("".join(lines))

        details, failures = check_env_example_completeness(env_example)

        # Every missing var must appear in failures
        for var in missing_vars:
            assert any(var in f for f in failures), (
                f"Expected failure for missing var {var!r}, but not found in: {failures}"
            )

        # The number of failures must equal the number of missing vars
        assert len(failures) == len(missing_vars), (
            f"Expected {len(missing_vars)} failures for missing vars {missing_vars}, "
            f"but got {len(failures)}: {failures}"
        )


@given(
    extra_vars=st.lists(
        st.text(
            alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ_",
            min_size=1,
            max_size=20,
        ).filter(lambda s: s not in REQUIRED_ENV_VARS and s[0].isalpha()),
        min_size=0,
        max_size=5,
        unique=True,
    ),
    values=st.lists(safe_value_strategy, min_size=7, max_size=7),
)
@settings(max_examples=100)
def test_all_required_vars_present_with_extras_passes(
    extra_vars: list[str],
    values: list[str],
):
    """
    # Feature: deploy-readiness-audit, Property 13: All required env vars documented in .env.example

    For any .env.example that contains all required variables (plus any number
    of extra variables), the checker SHALL produce no failures.

    Validates: Requirements 8.4
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)
        env_example = tmp_path / ".env.example"

        lines = [f"{var}={val}\n" for var, val in zip(REQUIRED_ENV_VARS, values)]
        for extra in extra_vars:
            lines.append(f"{extra}=extravalue\n")

        env_example.write_text("".join(lines))

        details, failures = check_env_example_completeness(env_example)
        assert failures == [], (
            f"Expected no failures when all required vars are present, "
            f"but got: {failures}"
        )


@given(
    var=st.sampled_from(REQUIRED_ENV_VARS),
    value=safe_value_strategy,
    comment_prefix=st.text(
        alphabet="abcdefghijklmnopqrstuvwxyz ",
        min_size=0,
        max_size=20,
    ),
)
@settings(max_examples=100)
def test_commented_out_var_not_counted_as_documented(
    var: str,
    value: str,
    comment_prefix: str,
):
    """
    # Feature: deploy-readiness-audit, Property 13: All required env vars documented in .env.example

    A required variable that only appears in a comment line (starting with #)
    SHALL NOT be counted as documented — only uncommented key=value lines count.

    Validates: Requirements 8.4
    """
    # Build a file where the var only appears in a comment
    other_vars = [v for v in REQUIRED_ENV_VARS if v != var]

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)
        env_example = tmp_path / ".env.example"

        lines = [f"# {comment_prefix}{var}={value}\n"]  # commented out
        lines += [f"{v}=somevalue\n" for v in other_vars]
        env_example.write_text("".join(lines))

        details, failures = check_env_example_completeness(env_example)

        assert any(var in f for f in failures), (
            f"Expected failure for {var!r} that only appears in a comment, "
            f"but not found in failures: {failures}"
        )


@given(
    var=st.sampled_from(REQUIRED_ENV_VARS),
    value=safe_value_strategy,
)
@settings(max_examples=100)
def test_each_required_var_individually_detected_when_missing(
    var: str,
    value: str,
):
    """
    # Feature: deploy-readiness-audit, Property 13: All required env vars documented in .env.example

    For each individual required variable, when it is the only one missing from
    .env.example, the checker SHALL produce exactly one failure naming that variable.

    Validates: Requirements 8.4
    """
    other_vars = [v for v in REQUIRED_ENV_VARS if v != var]

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)
        env_example = tmp_path / ".env.example"

        lines = [f"{v}=somevalue\n" for v in other_vars]
        env_example.write_text("".join(lines))

        details, failures = check_env_example_completeness(env_example)

        assert len(failures) == 1, (
            f"Expected exactly 1 failure when only {var!r} is missing, "
            f"but got {len(failures)}: {failures}"
        )
        assert var in failures[0], (
            f"Expected failure to mention {var!r}, but got: {failures[0]!r}"
        )
