"""
Property-based tests for health check logic.

# Feature: deploy-readiness-audit, Property 1: Health check response shape
# Feature: deploy-readiness-audit, Property 2: Health check retry exhaustion produces FAIL

Validates: Requirements 1.1, 1.2, 1.4
"""
from __future__ import annotations

from typing import Any

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from scripts.checks.health import validate_health_response, _poll_service
from scripts.models import Status

# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------

# A non-empty, non-whitespace-only string
nonempty_str = st.text(min_size=1, max_size=50).filter(lambda s: s.strip())

# A valid health response body
valid_health_body = st.fixed_dictionaries(
    {
        "status": st.just("ok"),
        "service": nonempty_str,
        "version": nonempty_str,
    }
)

# An invalid health response body — generated by mutating one or more required fields
invalid_health_body = st.one_of(
    # Wrong status value
    st.fixed_dictionaries(
        {
            "status": st.text().filter(lambda s: s != "ok"),
            "service": nonempty_str,
            "version": nonempty_str,
        }
    ),
    # Missing status key
    st.fixed_dictionaries(
        {
            "service": nonempty_str,
            "version": nonempty_str,
        }
    ),
    # Empty service name
    st.fixed_dictionaries(
        {
            "status": st.just("ok"),
            "service": st.just(""),
            "version": nonempty_str,
        }
    ),
    # Whitespace-only service name
    st.fixed_dictionaries(
        {
            "status": st.just("ok"),
            "service": st.text(alphabet=" \t\n", min_size=1, max_size=10),
            "version": nonempty_str,
        }
    ),
    # Missing service key
    st.fixed_dictionaries(
        {
            "status": st.just("ok"),
            "version": nonempty_str,
        }
    ),
    # Empty version string
    st.fixed_dictionaries(
        {
            "status": st.just("ok"),
            "service": nonempty_str,
            "version": st.just(""),
        }
    ),
    # Whitespace-only version string
    st.fixed_dictionaries(
        {
            "status": st.just("ok"),
            "service": nonempty_str,
            "version": st.text(alphabet=" \t\n", min_size=1, max_size=10),
        }
    ),
    # Missing version key
    st.fixed_dictionaries(
        {
            "status": st.just("ok"),
            "service": nonempty_str,
        }
    ),
    # Non-dict body
    st.one_of(st.none(), st.integers(), st.lists(st.text())),
)

# Non-200 HTTP status codes (client/server errors)
non_200_status_code = st.integers(min_value=100, max_value=599).filter(
    lambda c: c != 200
)


# ---------------------------------------------------------------------------
# Property 1: Health check response shape
# ---------------------------------------------------------------------------

@given(valid_health_body)
@settings(max_examples=100)
def test_valid_health_response_is_accepted(body: dict[str, Any]):
    """
    # Feature: deploy-readiness-audit, Property 1: Health check response shape

    For any backend service, a successful GET /health response SHALL be a JSON
    object containing "status": "ok", a non-empty service name field, and a
    non-empty version string field.

    The validator MUST accept any such response.

    Validates: Requirements 1.1, 1.2
    """
    ok, reason = validate_health_response(body)
    assert ok is True, (
        f"Expected valid body to be accepted, but got rejection reason: {reason!r}\n"
        f"Body: {body}"
    )


@given(invalid_health_body)
@settings(max_examples=100)
def test_invalid_health_response_is_rejected(body: Any):
    """
    # Feature: deploy-readiness-audit, Property 1: Health check response shape

    The validator MUST reject any response that does not contain all three
    required fields with valid values.

    Validates: Requirements 1.1, 1.2
    """
    ok, reason = validate_health_response(body)
    assert ok is False, (
        f"Expected invalid body to be rejected, but validator accepted it.\n"
        f"Body: {body}"
    )
    # The rejection reason must be a non-empty string
    assert isinstance(reason, str) and reason.strip(), (
        f"Rejection reason must be a non-empty string, got: {reason!r}"
    )


# ---------------------------------------------------------------------------
# Property 2: Health check retry exhaustion produces FAIL
# ---------------------------------------------------------------------------

@given(
    service_name=st.text(min_size=1, max_size=30).filter(str.strip),
    bad_status_code=non_200_status_code,
    num_retries=st.integers(min_value=1, max_value=5),
)
@settings(max_examples=100)
def test_retry_exhaustion_always_produces_fail(
    service_name: str,
    bad_status_code: int,
    num_retries: int,
):
    """
    # Feature: deploy-readiness-audit, Property 2: Health check retry exhaustion produces FAIL

    For any backend service that returns a non-200 response on every attempt,
    after exhausting all retry attempts the audit runner SHALL record a FAIL
    status — never PASS or SKIP.

    Validates: Requirements 1.4
    """
    call_count = 0

    def always_bad_http_get(url: str) -> tuple[int, Any]:
        nonlocal call_count
        call_count += 1
        return bad_status_code, {"error": "simulated failure"}

    status, details, failures = _poll_service(
        name=service_name,
        url=f"http://localhost:9999/health",
        max_retries=num_retries,
        retry_delay=0,  # no delay in tests
        http_get=always_bad_http_get,
    )

    assert status == Status.FAIL, (
        f"Expected FAIL after {num_retries} retries with HTTP {bad_status_code}, "
        f"but got {status!r}"
    )
    assert status != Status.PASS, (
        f"Status must never be PASS when all retries return HTTP {bad_status_code}"
    )
    assert status != Status.SKIP, (
        f"Status must never be SKIP when all retries return HTTP {bad_status_code} "
        f"(SKIP is only for connection refused)"
    )
    # Verify the correct number of attempts were made
    assert call_count == num_retries, (
        f"Expected exactly {num_retries} HTTP calls, but made {call_count}"
    )


@given(
    service_name=st.text(min_size=1, max_size=30).filter(str.strip),
    bad_status_code=non_200_status_code,
)
@settings(max_examples=100)
def test_retry_exhaustion_with_five_retries_always_produces_fail(
    service_name: str,
    bad_status_code: int,
):
    """
    # Feature: deploy-readiness-audit, Property 2: Health check retry exhaustion produces FAIL

    Specifically verifies the 5-retry case mandated by Requirement 1.4:
    after exactly 5 failed attempts the result is always FAIL.

    Validates: Requirements 1.4
    """
    call_count = 0

    def always_bad_http_get(url: str) -> tuple[int, Any]:
        nonlocal call_count
        call_count += 1
        return bad_status_code, None

    status, details, failures = _poll_service(
        name=service_name,
        url="http://localhost:9999/health",
        max_retries=5,
        retry_delay=0,
        http_get=always_bad_http_get,
    )

    assert status == Status.FAIL, (
        f"Expected FAIL after 5 retries with HTTP {bad_status_code}, "
        f"but got {status!r}"
    )
    assert call_count == 5, (
        f"Expected exactly 5 HTTP calls, but made {call_count}"
    )
    # Failures list must be non-empty
    assert len(failures) > 0, "Failures list must not be empty on FAIL status"
